name: parkly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  firebase_auth: ^4.4.0
  provider: ^6.0.0
  google_fonts: ^5.0.0
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: 9.2.0
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_illustration.png
